
localization["cn"]= {
        en: '英文',
        my: '国语',
        cn: '中文 (简体)',
        default_currency: "RM",
        language_text: '中文 (简体)',
        language_real:'语言',
        login_button: '登入',
        login_username: '用户名',
        login_password: '密码',
        forgot_button:"忘记?",
        mpos_login:"MPOS 登入",

        dash_notificationBtn: '通知',
        dash_settingBtn: '设置',
        dash_logOutBtn: '登出',
        dash_welcomeText: '欢迎, ',
        dash_visitText: '您上次上线访问是在',
        dash_currencyText: '汇率',
        dash_newCusText: '新客户',
        dash_quotationText: '报价',
        dash_newCFFBtn: '新 CFF',
        dash_discoveryBtn: '起始于探索',
        dash_calculateBtn: '计算',
        dash_myCusText: '我的客户',
        dash_myProText: '我的提案',
        dash_epayText: '线上付款',
        dash_brocText: '小册和线上表格',
        dash_clear: '消除所有',
        dash_general: '普通',
        dash_cff: 'CFF 通知',
        dash_doc: '文件',
        dash_event: '最近的活动',
        dash_oldEvent: '旧活动',
        dash_reject: 'CFF 驳回',
        dash_approve: '通过',
        dash_newProduct: '新产品目录',
        dash_change: '做出的调整将会在整个mPOS生效',
        dash_inflation: '通货膨胀率',
        dash_set: '为Customer Fact Finding调整所需通货膨胀率',
        dash_enter: '输入',
        dash_backup: '自动备份的选择',
        dash_sync: '切换您的备份连接',
        dash_wifi: '只限无线',
        dash_wifid: '无线与移动数据',
        dash_lastbackup:'XXtranslationBC',
        dash_pass: '更换密码',
        dash_newPass: '为您的帐号设置新的密码',

        cancel_btn: "取消",
        edit_btn: "修改",
        logout_btn: "登出",

        cl_title: '我的客户',
        cl_sort: '排序',
        cl_name: '姓名',
        cl_importBtn: '导入',
        cl_individual: '个人',
        cl_new: '新客户',
        cl_corporate: '企业',
        cl_placeholder: '查找 名字, 身份证, 电话号码',
        cl_placeholderCo: '查找',
        cl_idType: '证件种类',
        cl_idNo: '证件号',
        cl_mobile: '电话号码',
        cl_gender: '性别',
        cl_pref: '首选',
        cl_all: '全部客户',
        cl_coName: '公司名字',
        cl_contact: '联络人',
        cl_office: '办公室号码',
        cl_import: "导入客户",

        im_title: '从MCIF导入客户',
        im_deselect: '取消选择',
        im_import: '导入已选',
        im_placeholder: '搜索',

        mcif_keep: '保留全部',
        mcif_overwrite: '覆盖全部',
        mcif_keepBtn: '保留现存',
        mcif_overwriteBtn: '从MCIF覆盖',

        cm_custMgt: "客户管理",
        cm_newCus: '新的客户',
        cm_preffered: '标签为首选',
        cm_detail: '详情',
        cm_relationship: '关系',
        cm_cff: "CUSTOMER FACT FINDING",
        cm_quotation: '报价',
        cm_quotationText: '报价',
        cm_proposal: '提案',
        cm_exist: '没有存在的',
        cm_rel: '关系',
        cm_addRel: '添加关系',
        cm_editList: '编辑目录',
        cm_cffText: 'Customer Fact Finding',
        cm_profile: "Profile",
        cm_record: '计录',
        cm_newCff: '添加CFF',
        cm_quotationNo: 'QUOTATION NO.',
        cm_cffNo: 'CFF NO.',
        cm_life: '受保人',
        cm_updated: '上次更新',
        cm_complete: '完成',
        cm_void: '作废',
        cm_cffBtn: 'Customer Fact Find',
        cm_confirmBtn: '确认咨询',
        cm_duplicateBtn: '重复',
        cm_annual: '年度保费',
        cm_premium: "保费",
        cm_sum: '保险金额',
        cm_term: '期',
        cm_delete: '删除',
        cm_deleteselection: 'XXtranslationBC',
        cm_newQuotation: '添加新保价',
        cm_genProposal: '生成提案',
        cm_importCustomer: "导入客人",
        cm_lastUpdated: "最后更新",
        cm_generateProposal: "XXtranslationBC",
        cm_formName: 'Name as per ID',
        cm_formRelName: 'Name as per ID',
        cm_formAlias: 'Alias',
        cm_formNickname: 'Nickname',
        cm_formIDtype: 'ID Type',
        cm_formIDnumber: 'ID Number',
        cm_formDOB: 'Date of Birth',
        cm_formANB: 'Age Next Birthday',
        cm_formGender: 'Gender',
        cm_formRace: 'Race',
        cm_formMobile: 'Mobile No.',
        cm_formHouse: 'House No.',
        cm_formOffice: 'Office No.',
        cm_formEmail: 'Email',
        cm_formMarry: 'Marital Status',
        cm_formPersonal: 'Personal Details',
        cm_formResident: 'Residential Address',
        cm_formMailing: 'Mailing Address',
        cm_formAddress: 'Address Line',
        cm_formPost: 'Postcode',
        cm_formTown: 'Town',
        cm_formState: 'State',
        cm_formCountry: 'Country',
        cm_formSameAs: 'Same as Residential Address',
        cm_formSameAsMain: 'Same as Main Customer',
        cm_formAddMail: 'Additional Address',
        cm_formRelated: 'Related Party',
        cm_formRelationship: 'Relationship',

        pm_proposalNo: 'MPOS 提案号码.',
        pm_policyNo: '保单号码',
        pm_title: '管理提案',
        pm_myProposal: '我的提案',
        pm_cffReview: '检阅 CFF',
        pm_placeholder: '搜索',
        pm_agent: '经纪人',
        pm_initial: '成功初始注册',
        pm_waitingInitial: 'XXtranslationBC',
        pm_initialProgress: 'XXtranslationBC',
        pm_waitingData: 'XXtranslationBC',
        pm_dataProgress: 'XXtranslationBC',
        pm_waitingVerification: 'XXtranslationBC',
        pm_verificationProgress: 'XXtranslationBC',
        pm_euaProgress: 'XXtranslationBC',
        pm_waitingUnderwriting: 'XXtranslationBC',
        pm_underwriting: '承保进展',
        pm_amendmentProgress: 'XXtranslationBC',
        pm_accept: 'XXtranslationBC',
        pm_conditionAccept: '有条件接受',
        pm_declined: '拒绝',
        pm_postponed: '延期',
        pm_inforce: '现行',
        pm_withdrawn: '撤销',
        pm_pendingCompletion: 'XXtranslationBC',
        pm_cffRejected: 'CFF驳回',      
        pm_approved: '批准',
        pm_pendingApprove: '待批准',
        pm_subProgress_MP: 'XXtranslationBC',
        pm_subProgress_ESUB: 'XXtranslationBC',
        pm_pendingApproval: 'XXtranslationBC',
        pm_rejected: '驳回',
        pm_planName: '计划名称',
        pm_status: '状态',
        pm_submitDate: '提交日期',
        pm_commenceDate: '生效日期',
        pm_proposerName: '投保人名称',
        pm_life: 'XXtranslationBC',

        re_title: '小册子和表格',
        re_newest: '最新',
        re_tabForm: '表格',
        re_tabEform: '电子表格',
        re_tabProduct: '产品宣传手册',
        re_formPlaceholder: '查找',
        re_OccupationPlaceholder: 'XXtranslationBC',
        re_eformPlaceholder: '查找',
        re_productPlaceholder: '查找',
        re_formName: '表格名称',
        re_code: '编码',
        re_eformName: '电子表格名称',
        re_productName: '产品手册名称',
        re_productCategory: '产品手册类别',
        re_submitDate: '提交日期',
        re_submitProgress: '提交进度',
        re_frequent: '经常使用',
        re_allForm: '所有表格',
        re_alleForm: '所有电子表格',
        re_allBrochure: '所有产品手册',
        re_new: '新',
        re_noRecords: 'No records found',
        re_byFormName: 'Form Name',
        re_byFormCategory: 'Form Category',
        re_byProductName: 'Product Name',
        re_byProductCategory: 'Product Category',
        re_productLanguage: 'Product Language',
        re_formLanguage: 'Form Language',
        re_view: '视图',
        re_retry: '重试',
        re_cancel: '取消',

        rfa_requestForAdmendment: '修改申请',
        rfa_proposalNo: '提案号码',
        rfa_policyNo: '保单号码',
        rfa_identificationType: '证件种类',
        rfa_MsiaIC: '马来西亚IC',
        rfa_passport: '护照',
        rfa_IdNo: '证件号',
        rfa_importantNote: '重要笔录',
        rfa_modeOfPayment: '付款方式',
        rfa_methodOfPayment: 'XXtranslationBC',
        rfa_monthly: '每月一次',
        rfa_yearly: '每年一次',
        rfa_cash: '现款',
        rfa_cheque: '支票',
        rfa_basicPlanTo: '基本计划',
        rfa_premiumTo: '额外',
        rfa_reduceSumAssured: '减少保险金额',
        rfa_riderTo: '附件于',
        rfa_backdateCommencementDate: '追溯生效日期',
        rfa_cancellationOfBackdating: '回溯取消',
        rfa_changeOfMailingAddr: '邮寄地址更改',
        rfa_changeOfResidentialAddr: '住家地址更改',
        rfa_others: '其他',
        rfa_otherThanlifeToBeAssured: '受保人以外',
        rfa_witness: '见证人 (Agent)',
        rfa_submit: '提交',
        rfa_changeInPremium: '注意：任何改变 in premium will auto change the premium waiver rider sum assured (if applicable).',
        rfa_noteInfo: "注意：Monthly mode is only applicable for payment method GIRO, Credit Card  or Banker's Order",
        rfa_noteInfo2: '注意：GIRO/Credit Card 的使用者, 请填 GIRO/Easi-Pay Application Form.',
        rfa_proposerName: '建议人',
        rfa_lifeToBeAssuredName: '受保人名字',
        rfa_planCode: '提案码',
        rfa_enter: '进入',
        rfa_addrLine: '地址',
        rfa_sumAssured: '保额 (RM)',
        rfa_postcode: '邮编',

        cff_myAssets: '我的资产',
        cff_myLiability: '我的负债',
        cff_fixedAssets: '固定资产',
        cff_investment: '投资',
        cff_saving: '存款',
        cff_epf: '公积金',
        cff_total: '总共',
        cff_totalNetWorth: '总净值',
        cff_mortgage: '抵押',
        cff_others: '其他',
        cff_myIncome: '我的收入',
        cff_myExpenditure: '我的开销',
        cff_example1: '(e.g 信用卡, etc)',
        cff_example2: '(e.g 房租, 花红, etc)',
        cff_example3: '(e.g  家庭, 教育, 其他)',
        cff_totalMonthlyExpenses: '每月总费用',
        cff_cashFlowSummary: '现金流量汇总',
        cff_noDependant: '我没有负担',
        cff_dependant: '依赖他人者',
        cff_relationship: '关系',
        cff_gender: '性别',
        cff_dob: '生日日期',
        cff_yearToSupport: '需要负担的年数',
        cff_noPolicy: '我现在没有任何保单',
        cff_existingPolicy: '现有保单',
        cff_annualPremium: '年保费',
        cff_sumAssured: '保额',
        cff_lifeToBeAssured: '受保人',
        cff_planningFor: '计划给予',
        cff_maturity: '成人之日',
        cff_low: '低',
        cff_hight: '高',
        cff_dragAndPlace: '移动图标来决定您优先的事项',
        cff_protection: '保护',
        cff_healthCare: '医药',
        cff_debt: '债务取消',
        cff_education: '教育',
        cff_retirement: '退休',
        cff_savingInvest: 'Savings & Investment',
        cff_investTimeframe: 'Investment Time Frame',
        cff_expectedReturn: 'Expected annual % return',
        cff_investmentPerMonth: 'Amount to be allocated for Investment per month',
        cff_existingResource: 'Existing Resource',
        cff_capitalSum: 'Capital Sum Required',
        cff_childEducation: 'Children Education',
        cff_rateReturn: 'Rate of Return',
        cff_inflationRate: 'Inflation Rate',
        cff_yearsToTertiary: 'Years to tertiary education',
        cff_durationStudy: 'Duration of Study',
        cff_currentYearlyCost: 'Current yearly cost (tuition + living)',
        cff_existingEduFund: 'Existing children education fund',
        cff_amountNeededForEdu: 'Amount needed for tertiary education',
        cff_retireIncome: 'Retirement Income',
        cff_noForRetire: 'No of years to retirement',
        cff_annualNeedForRetire: 'Annual amount needed for retirement',
        cff_noReceiveIncome: 'No. of years to receive this income',
        cff_existingRetireIncome: 'Existing retirement income',
        cff_amountNeedForRetire: 'Amount needed for retirement',
        cff_incomeProtection: 'Income Protection',
        cff_annualNeedForDisability: 'Annual Income needed in event of disability',
        cff_yearsNeededForProtection: 'Years needed for this annual income to be protected',
        cff_existingLifeInsurance: 'Existing life insurance',
        cff_insuranceProtectionNeeded: 'Amount of life insurance protection needed',
        cff_medicalPlanning: 'Medical/Health Care Planning',
        cff_criticalIllness: 'Critical Illness',
        cff_amountNeededForTreatment: 'Amount needed for treatment of critical illness',
        cff_existingCriticalIllness: 'Existing critical illness protection',
        cff_amountOfCriticalIllness: 'Amount of life critical illness needed',
        cff_hospitalisation: 'Medical / Hospitalisation',
        cff_amountNeededForMedical: 'Amount needed for medical/hospitalisation',
        cff_existingMedicalPlan: 'Existing medical/hospitalisation plan',
        cff_amountOfMedical: 'Amount of Medical / Hospitalisation needed',
        cff_debtCancellation: 'Debt Cancellation',
        cff_outstandingLoan: 'Outstanding Loan',
        cff_yearsLeftForSettlement: 'No. of years left for loan settlement',
        cff_existingDebtCancelPlan: 'Existing debt cancellation plan',
        cff_amountNeededForDebtCancel: 'Amount needed for debt cancellation',
        cff_roaExistingProposalError: '此<?>不能被选择，因为它附加到另一个提案',
        cff_wealthSectionError: '请填写<?>。',
        cff_wealthProtectionPageError: '财富保护页面',
        cff_wealthAccumulationPageError: '财富积累页',
        cff_wealthProtectionIncomeLimitError: '所需的人身保险保障金额必须至少<?>。',
        cff_wealthProtectionMedicalLimitError: '所需的危重疾病量或所需医疗/住院费用必须至少<?>。',
        cff_wealthProtectionDebtLimitError: '取消债务所需的金额必须至少<?>。',
        cff_wealthAccumulationSavingLimitError: '每个月投入的金额必须至少<?>。',
        cff_wealthAccumulationChildrenLimitError: '儿童高等教育所需的金额必须至少<?>。',
        cff_wealthAccumulationRetirementLimitError: '退休所需的金额必须至少<?>。',
        cff_roaTotalPremiumVsInsurancePlanning: '所选择的计划费用总额不能超过保险计划金额<?>。',
        cff_roaMissingCompletePlanOne: '请至少创建一个优先级为1的报价单。',
        cff_coaMissingCompletePlanOne: '请至少选择一个优先级为1的报价，以确认建议，然后再转到确认部分。',
        cff_changeInsurancePlanningPrompt: '确认建议将被重置。确认更改现行保险计划金额？',
        cff_changeLifePriorityPrompt: '有一个现有的记录在这个生活优先级标记的建议。你确定要改变吗？',
        cff_lifePriorityOneError: '请与排名1至少选择一个生活优先。',
        cff_lifePrioritySequentialError: '请按顺序选择生命优先号。',
        cff_riskProfileReminder: 'Your risk profile shall determine the choice of funds you selected prior to proposal submission (for Investment-linked plans only).',
        cff_changeRiskProfilePrompt: 'There is an existing record of advice tagged under this risk tolerance profile. Are you sure you want to change?',
        cff_riskProfileIncomplete: 'Please complete Risk Profile section.',
        cff_riskProfileYReturnMismatch: 'Please ensure Fund Selection is matching with Risk Tolerance Profile.<br><br>Very secure: not exceeding <?>%<br>Moderately secure: <?>% - <?>%<br>Balanced: <?>% - <?>%<br>Dynamic: <?>% - <?>%<br>Very Dynamic: <?>% - <?>%',
        form_select: '选择',
        form_enter: '输入',
        form_currency: 'RM',
        form_year: '年',

        ps_quotationNo: 'Quotation No',
        ps_life: '受保人',
        ps_sumassured: 'Sum assured',
        ps_coverterm: 'Cover term',
        ps_premiumterm: 'Premium term',
        ps_totalpremiumamount: 'Total Premium',
        ps_noofunits: 'No of units',
        ps_premium: '保费',
        ps_supplementarybenefits: 'Rider / Supplementary benefits',
        ps_ridercode: 'Rider code',
        ps_ridername: 'Rider name',
        ps_funddetails: 'Fund details',
        ps_strategypackage: 'Strategy Package',
        ps_horizon: 'Investment Horizon',
        ps_fundname: 'Funds',
        ps_allocation: 'Allocation %',
        ps_frompolicyyear: 'From policy year',
        ps_topolicyyear: 'To policy year',
        ps_proposer: '提供',
        ps_plan: '计划',
        ps_insurance_history: '保险史',
        ps_health_lifestyle: '健康与生活方式',
        ps_appointment: 'Nomination',
        ps_supplementary_forms: '补充表格',
        ps_capture_image: '摄取图像',
        ps_acknowledgement: '认证',
        ps_summary: '总结',
        ps_premiumpaymentinstruction: 'Premium payment instruction',
        ps_paymentmode: 'Payment mode',
        ps_yearly: '每年一次',
        ps_halfyearly: 'Half yearly',
        ps_quaterly: 'Quarterly',
        ps_monthly: '每月一次',
        ps_paymentmethod: 'Payment method',
        ps_family_history: 'XXtranslationBC',
        ps_cash: '现款',
        ps_cheque: '支票',
        ps_giro: 'Giro',
        ps_creditcard: 'Credit card',
        ps_bankersorder: 'Banker`s order',
        ps_singlepremium: 'Single premium top up',
        ps_chargecreditcard: 'Charge to credit card',
        ps_backDateCommencementDate: 'Backdate Commencement date',
        ps_backdatingamount: 'Backdating amount',
        ps_totalpremium: 'Total premium',
        ps_vouchercode: 'Voucher code',
        ps_voucheramount: 'Voucher amount',
        ps_totalpayable: 'Total payable',
        ps_terms: "Note: All cheques for premium payment are to be crossed account payee (not negotiable) and made payable to GREAT EASTERN LIFE ASSURANCE (MALAYSIA) BERHAD. The Proposer's name and NRIC/Passport No. must be written on the reverse side of the cheque and if the Life to be Assured and the Proposer are different, the name of the Life to be Assured should also be indicated.",
        ps_familydiscount: 'Family discount package',
        ps_staffdiscount: 'Staff discount',
        ps_proposalfamily: 'Proposal / Policy no. of family members and relationship',
        ps_insuranceless: 'Existing Insurance Less Than 10 Years',
        ps_companyname: 'Company Name',
        ps_yearissued: 'Year Issued',
        ps_lifebenefit: 'Life Benefit',
        ps_disablilitybenefits: 'Total & Permanent Disability Benefits',
        ps_criticalillness: 'Critical Illness / Living Assurance',
        ps_accidentbenefits: 'Accident Benefits',
        ps_healthinsurance: 'Medical & Health Insurance',
        ps_disabilityincome: 'Disability Income',
        ps_insurancemore: 'Existing Insurance More Than 10 Years',
        ps_existinginsurance: 'Particulars of Existing and/or Concurrent Insurance Coverage',
        ps_historyq1: 'Do you have any existing insurance including those now being proposed to other companies?',
        ps_insuranceproposeless: 'Existing insurance including those now being proposed that is LESS than 10 years.',
        ps_addinsurance: 'Add Insurance',
        ps_insuranceproposemore: 'Existing insurance including those now being proposed that is MORE than 10 years.',
        ps_historyq2: 'Has any proposal, reinstatement or application for renewal of insurance on your life (including those now being proposed to other companies) ever been declined, postponed, rated, restricted or in any way modified or subjected to additional terms? If "YES",please give details.',
        ps_yes: 'Yes',
        ps_historyq3: 'Is this proposal replacing or intended to replace any existing policy with us or any other insurance company? If your answer is "YES", please complete the "Declaration Form on Replacement of Life Insurance Policy".',
        ps_historyq4: 'Have you surrendered or terminated any of your existing life insurance policy(ies) in the last 12 months and now to be replaced with the application of this new policy? If your answer is "YES", please complete the "Declaration Form on Replacement of Life Insurance Policy".',

        quo_fullQuote  : "Full Quotation",
        quo_iQuote : "iQuote",
        quo_pdsInclusionRiders : "PDS for Inclusion of Riders",
        quo_bipds_emailcontent_default : "Here is the quotation",
        quo_bipds_emailcontent_inv : "Here is the quotation<br/><br/><b>About your password</b><br/>For your security, the attachment will be password protected. To view your quotation, simply enter your default password in the following order.<br/>If your name registered is Chris Lee, and your mobile number is 60123344550.<br/>The default password is as follows:<br/>C60123344550<br/>where C is the capitalized first letter of your name and 60123344550 is the full mobile phone number recorded, in event there is no mobile number record, house phone number and office phone number will be used in this precedence.",
        quo_bipds_emailcontent_corp : "Here is the quotation<br/><br/><b>About your password</b><br/>For your security, the attachment will be password protected. To view your quotation, simply enter your default password in the following order.<br/>If your company’s name registered is MegaTop, and your office number is 60123344550.<br/>The default password is as follows:<br/>M60123344550<br/>where C is the capitalized first letter of your company name and 60123344550 is the full office phone number recorded.",
        
        /*Quotation Investment Strategy Names*/
        strategyName_0 : "My Choiced",
        strategyName_1 : "Very Secure",
        strategyName_7 : "My Choiced Investor Profile",
        strategyName_8 : "Very Secure(Islamic Funds)",
        strategyName_17 : "Universal",
        strategyName_18 : "Moderately Secure",
        strategyName_19 : "Balanced",
        strategyName_20 : "Moderately Dynamic",
        strategyName_21 : "Dynamic",
        strategyName_22 : "Very Dynamic",
        strategyName_23 : "Moderately Secure(Islamic Funds)",
        strategyName_24 : "Balanced(Islamic Funds)",
        strategyName_25 : "Moderately Dynamic(Islamic Funds)",
        strategyName_26 : "Dynamic(Islamic Funds)",
        strategyName_27 : "Very Dynamic(Islamic Funds)",
    };
